services:
  database:
    image: postgres:14
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: certificados_db
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-postgres/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  api:
    build:
      context: ./api
    environment:
      - DATABASE_URL=postgresql://username:password@database:5432/certificados_db
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672  # Corrigido
      - PORT=3000
    depends_on:
      - database
      - rabbitmq
    ports:
      - '3000:3000'

  worker:
    build:
      context: ./worker
    environment:
      - RABBITMQ_URL=amqp://user:password@rabbitmq:5672  # Corrigido
      - DATABASE_URL=postgresql://username:password@database:5432/certificados_db
    depends_on:
      - rabbitmq
      - database

volumes:
  db_data:



